import Head from 'next/head'
import Header from '../components/header'
import Start from '../components/start'
import styles from '../styles/About.module.scss'


export default function About() {
  return (
    <>
      <Head>
        <title>Swarmtrust | About</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
          <Header />
          <div className={styles.main}>

          </div>
        
      </main>
    </>
  )
}
