import * as React from 'react';
import Head from 'next/head'
import Header from '../components/header'
import Showroom from '../components/showroom'
import styles from '../styles/Watch-out-together.module.scss'

export default function WatchOutTogether() {
  const [defaultText, setDefaultText] = React.useState<string>('')
  const text:string = "Hallo"

  const setInfoText = () =>{
    setDefaultText(text)
  }

  function changePoap(trait1:string, trait2:string, trait3:string) {


  }

  return (
    <>
      <Head>
        <title>Swarmtrust | Watch out together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.body}>
        <Header />
      <main className={styles.main}>
          <div className={styles.containerPoap}>
            <div className={styles.poap}>
              <Showroom/>
            </div>
            <div className={styles.text}>

                <p>{defaultText}</p>
            </div>

          </div>
          <div className={styles.containerFilter}>

            {/* Trait 1 */}
           <div className={styles.traitWrapper}>
                <div className={styles.trait}>
                    <h3>Trait 1</h3>
                    <button onClick={setInfoText}>Arrow</button>
                </div>
                <div>

                </div>
                <hr className={styles.separator}></hr>
            </div>

            {/* Trait 2 */}
            <div className={styles.traitWrapper}>
                <div className={styles.trait}>
                    <h3>Trait 2</h3>
                    <button>Arrow</button>
                </div>
                <div>

                </div>
                <hr className={styles.separator}></hr>
            </div>
            
            {/* Trait 3 */}
            <div className={styles.traitWrapper}>
                <div className={styles.trait}>
                    <h3>Trait 3</h3>
                    <button>Arrow</button>
                </div>
                <div>

                </div>
                <hr className={styles.separator}></hr>
            </div>
            
          </div>

        
      </main>
      </div>

      <script src="three.min.js"></script>
    </>
  )
}
