import * as React from 'react';
import Head from 'next/head'
import Header from '../components/header'
import Showroom from '../components/showroom'
import styles from '../styles/Watch-out-together.module.scss'
import {Trait} from '../components/traits'

export default function WatchOutTogether() {
  const [defaultText, setDefaultText] = React.useState<string>('')
  const text:string = "Hallo"

  const setInfoText = () =>{
    setDefaultText(text)
  }

  function changePoap(trait1:string, trait2:string, trait3:string) {


  }

  return (
    <>
      <Head>
        <title>Swarmtrust | Watch out together</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.body}>
        <Header />
      <main className={styles.main}>
          <div className={styles.containerPoap}>
            <div className={styles.poap}>
              <Showroom/>
            </div>
            <div className={styles.text}>

                <p>{defaultText}</p>
            </div>

          </div>
          <div className={styles.containerFilter}>
            <Trait/>
          </div>

        
      </main>
      </div>

      <script src="three.min.js"></script>
    </>
  )
}
