import {useRouter} from 'next/router'
import Head from 'next/head'
import Header from '../../components/header'
import Start from '../../components/start'
import MetamaskButton from '../../components/button'
import styles from '../../styles/Mint.module.scss'


export default function Mint() {
  const router = useRouter()
  const {tokenID} = router.query
  console.log(tokenID)
  return (
    <>
      <Head>
        <title>Swarmtrust | Mint</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.body}>
          <Header />
          <div className={styles.main}>
            <MetamaskButton />
            <h1>TokenID: {tokenID}</h1>
            

          </div>
        
      </main>
    </>
  )
}
